server:
  port: 8080
  address: 'localhost'

h2-console:
  port: 8081

spring:
  r2dbc:
    initialization-mode: always
    url: r2dbc:h2:mem:///testdb;MODE=MySQL;
    username: sa
    password:

logging:
  level:
    org.springframework.r2dbc: DEBUG
